spring:
  config:
    import: classpath:application-secret.yml

  datasource:
    url: ${local.db.url}
    username: ${local.db.username}
    password: ${local.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
  cloud:
    aws:
      s3:
        bucket: ${local.s3.bucket}
      region:
        static: ${local.s3.region.static}
        auto: false
      stack:
        auto: false
      credentials:
        access-key: ${local.s3.credentials.access-key}
        secret-key: ${local.s3.credentials.secret-key}
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    web:
      pageable:
        default-page-size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: team.dododok@gmail.com
    password: ${local.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

jwt:
  secret-key: ${local.jwt.secret-key}
  accessToken-validate-time: ${local.jwt.accessToken-validate-time}
  refreshToken-validate-time: ${local.jwt.refreshToken-validate-time}

oauth2:
  kakao:
    app-admin-key : ${local.oauth2.kakao.app-admin-key}