spring:
  config:
    import: classpath:application-secret.yml

  datasource:
    url: ${prod.db.url}
    username: ${prod.db.username}
    password: ${prod.db.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  cloud:
    aws:
      s3:
        bucket: ${prod.s3.bucket}
      region:
        static: ${prod.s3.region.static}
        auto: false
      stack:
        auto: false
      credentials:
        access-key: ${prod.s3.credentials.access-key}
        secret-key: ${prod.s3.credentials.secret-key}
  data:
    redis:
      host: ${prod.redis.host}
      port: ${prod.redis.port}
    web:
      pageable:
        default-page-size: 10

  mail:
    host: smtp.gmail.com
    port: 587
    username: team.dododok@gmail.com
    password: ${prod.mail.password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
jwt:
  secret-key: ${prod.jwt.secret-key}
  accessToken-validate-time: ${prod.jwt.accessToken-validate-time}
  refreshToken-validate-time: ${prod.jwt.refreshToken-validate-time}

oauth2:
  kakao:
    app-admin-key : ${prod.oauth2.kakao.app-admin-key}
